import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Lora } from "next/font/google";
import { MenubarDemo } from "@/components/MenuBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const inter = Lora({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} antialiased transition-colors `}
        style={{
          background: "linear-gradient(180deg, #F5F5F5 0%, #F5F5F5 100%)",
        }}
      >
        <MenubarDemo />
        {children}
      </body>
    </html>
  );
}

// position: relative;
// width: 1728px;
// height: 3089px;

// /* herbicide_overview_color */
